-- ZAYA — Supabase production database + storage setup
-- Run this in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  token text not null unique,
  title text not null,
  category text not null,
  price numeric(12,2) not null check (price >= 0),
  mrp numeric(12,2) not null check (mrp >= 0),
  colors jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  constraint products_colors_is_array check (jsonb_typeof(colors) = 'array')
);

create index if not exists products_created_at_idx
  on public.products (created_at desc);

create index if not exists products_category_idx
  on public.products (category);

alter table public.products enable row level security;

drop policy if exists "products_public_select" on public.products;
create policy "products_public_select"
on public.products
for select
to anon, authenticated
using (true);

drop policy if exists "products_authenticated_insert" on public.products;
create policy "products_authenticated_insert"
on public.products
for insert
to authenticated
with check (true);

drop policy if exists "products_authenticated_update" on public.products;
create policy "products_authenticated_update"
on public.products
for update
to authenticated
using (true)
with check (true);

drop policy if exists "products_authenticated_delete" on public.products;
create policy "products_authenticated_delete"
on public.products
for delete
to authenticated
using (true);

grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;

-- ------------------------------------------------------------
-- Recommended production admin allowlist
-- ------------------------------------------------------------
-- This table prevents an arbitrary signed-up customer account from
-- becoming an administrator.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

drop policy if exists "admin_users_self_select" on public.admin_users;
create policy "admin_users_self_select"
on public.admin_users
for select
to authenticated
using (user_id = auth.uid());

grant select on public.admin_users to authenticated;

-- After creating the first admin account through auth.html, run:
-- insert into public.admin_users (user_id)
-- values ('YOUR-AUTH-USER-UUID');

-- ------------------------------------------------------------
-- Storage bucket
-- ------------------------------------------------------------
-- Create the bucket in Dashboard > Storage > New bucket:
-- Name: product-images
-- Public bucket: ON
--
-- Supabase Storage public URLs are generated by getPublicUrl().
-- The upload itself remains protected by object RLS.

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

-- Authenticated admins may upload objects.
drop policy if exists "product_images_authenticated_insert" on storage.objects;
create policy "product_images_authenticated_insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'product-images'
  and exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  )
);

-- Authenticated admins may update objects.
drop policy if exists "product_images_authenticated_update" on storage.objects;
create policy "product_images_authenticated_update"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'product-images'
  and exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  )
)
with check (
  bucket_id = 'product-images'
  and exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  )
);

-- Authenticated admins may delete objects.
drop policy if exists "product_images_authenticated_delete" on storage.objects;
create policy "product_images_authenticated_delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'product-images'
  and exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  )
);

-- Public product image delivery is handled by the bucket being public.
-- Do NOT expose or use a service_role/secret key in browser JavaScript.

-- ------------------------------------------------------------
-- Optional seed example
-- ------------------------------------------------------------
-- Do not run this unless you have a real public image URL.
--
-- insert into public.products (token, title, category, price, mrp, colors)
-- values (
--   'mulmul-anarkali-set',
--   'Mulmul Embroidered Anarkali Set',
--   'Kurtas & Sets',
--   2499,
--   3499,
--   '[{"name":"Sage Green","hex":"#8A9A86","image":"https://example.supabase.co/storage/v1/object/public/product-images/mulmul-anarkali-set/example.jpg"}]'::jsonb
-- );
